sudo: false
dist: xenial
addons:
  chrome: stable
language: ruby
cache: bundler

services:
  - postgresql

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

before_script:
  - psql -c 'create database "webauthn-app_test";' -U postgres
  - yarn install

script:
  - bundle exec rake
  - TEST_BROWSER=headless_chrome bundle exec rake test:system
